version: "3.8"
services:
  postgres:
    image: postgres
    container_name: my-postgres
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - localhost-network

  mariadb:
    image: mariadb
    container_name: my-mariadb
    volumes:
      - ./storage/mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=root
      - MARIADB_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - localhost-network

  redis:
    image: redis
    container_name: my-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./storage/redis-data:/var/lib/redis
    restart: always
    networks:
      - localhost-network

  rabbitmq:
    image: rabbitmq
    container_name: my-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - ./storage/rabbitmq-data:/var/lib/rabbitmq
    restart: always
    networks:
      - localhost-network

  uptime:
    image: louislam/uptime-kuma:1
    container_name: my-uptime
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./storage/uptime-data:/app/data
    networks:
      - localhost-network

  minio:
    image: "quay.io/minio/minio"
    container_name: my-s3-minio
    command: server /data --console-address ":9090"
    volumes:
      - ./storage/minio-data:/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - localhost-network

volumes:
  storage:


networks:
  localhost-network:
    external: true
