version: "3.8"
services:
  postgres:
    image: postgres
    container_name: my-postgres
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my-local-network

  mariadb:
    image: mariadb
    container_name: my-mariadb
    volumes:
      - ./storage/mariadb-data:/var/lib/mysql
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - my-local-network

  redis:
    image: redis
    container_name: my-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./storage/redis-data:/var/lib/redis
    restart: always
    networks:
      - my-local-network

  minio:
    image: "quay.io/minio/minio"
    container_name: my-s3-minio
    command: server /data --console-address ":9090"
    volumes:
      - ./storage/minio-data:/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    restart: always
    ports:
      - "${MINIO_PORT}:9000"
      - "9090:9090"
    networks:
      - my-local-network

volumes:
  storage:

networks:
  my-local-network:
    driver: bridge
