version: "3.8"
services:
  postgres:
    image: postgres
    container_name: my-postgres
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my-local-network

  redis:
    image: "redis"
    container_name: my-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./storage/redis-data:/var/lib/redis
    restart: always
    networks:
      - my-local-network

networks:
  my-local-network:
    driver: bridge
