route:
  receiver: "telegram"
  routes:
    - matchers:
        - severity="critical"
      receiver: slack

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        username: "Prometheus"
        channel: "#monitoring"
        api_url: "https://hooks.slack.com/services/xxxxx"
        # text: "{{ .CommonAnnotations.description }}"
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}

  - name: 'telegram'
    telegram_configs:
    - bot_token: 1234567890:aBCd_eFGHjk_etc
      api_url: https://api.telegram.org
      chat_id: -1001234567890_1234
      # message_thread_id: 1234
