global:
  scrape_interval: 1m

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9191"]

  - job_name: "nodeexporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
# remote_write:
#   - url: "<Your Prometheus remote_write endpoint>"
#     basic_auth:
#       username: "<Your Grafana Username>"
#       password: "<Your Grafana Cloud Access Policy Token>"
