groups:
  - name: backend
    rules:
      - alert: Application down
        for: 1m
        expr: up{job="backend"} == 0
        labels:
          severity: critical
        annotations:
          title: App is down on {{ $labels.instance }}
          description: The app on instance {{ $labels.instance }} has been down for the past 1 minute.
  
  - name: "nodeexporter"
    rules:
      - alert: Application down
        for: 1m
        expr: up{job="nodeexporter"} == 0
        labels:
          severity: critical
        annotations:
          title: App is down on {{ $labels.instance }}
          description: The app on instance {{ $labels.instance }} has been down for the past 1 minute.
